# Executive Summary

## Background

Dr. Ariel Balter, an experienced scientist and data analyst, was diagnosed with ADHD and ASD later in life and is raising a teenager with both diagnoses. His desire to understand these challenges led him to study the scientific and social aspects of neurodiversity. Recent changes driven by autistic self-advocates and researchers have reshaped our understanding of autism, revealing significant gaps in support for autistic adults. These changes have led to controversies and arguments that are still unfolding, emphasizing the evolving nature of the understanding of autism.

Through his personal journey and interactions with the local autistic community, Dr. Balter identified significant gaps in services, support, and understanding for autistic adults without intellectual disabilities. He was struck by the level of unmet need he heard from his peers—people with skills, education, and abilities but struggling for reasons related to autism. These personal experiences led Dr. Balter to found Autism All Grown Up (AAGU) to address these gaps.

## Goals

The organization has four key objectives:

  1.  Facilitate connections and collaboration within the adult autistic community
2.  Identify the unmet needs of autistic adults and report on the causes
3.  Provide accurate, accessible, and up-to-date information and resources *for* autistic adults
4.  Provide accurate, accessible, and up-to-date information and resources *about* autism and *about* the autistic community

## Autism All Grown Up

Autism is all grown up, and it isn't pretty. The phrase "All Grown Up" captures the bittersweet realization that often occurs when one encounters an individual they knew as a child, only to find that their preconceived notions no longer fit the adult standing before them.

For decades, autism was seen as a developmental challenge that primarily affected children. Outdated notions of what constitutes genuine autism have cause adults to be overlooked by many people. Because so little research has acknowledged the lives of adults with autism, we know close to nothing about what successful adult development looks like. Some existing research suggests that autistic adults face reduced life expectancy, increased risk for physical disability, and an earlier onset of age-related cognitive concerns. Late-identified and never-identified autistic adults face unique challenges with respect to aging, and most of these "lost generation\[s\]" [@Wright2015] have not yet even been counted.

## The Nexus Approach

Rather than working on advocacy, Dr. Balter feels he can more directly serve the autistic community in Oregon by solving problems on the ground. Systemic and societal problems can only be addressed through advocacy. But many of the real-world problems faced by supporting existing infrastructure by increasing the connectivity and information flow. Rather than being a hub that consumes resources and provides services, AAGU will catalyze and strengthen relationships around it to form a *nexus*.
