# Funding Plan {#funding-plan}

We plan to fund AAGU in three phases: _Seed, Sprout, and Grow_.

We will primarily fund the _Seed_ phase through a GoFundMe crowdsource campaign. We hope to raise seed money of \$2k-\$3k per week to jump start formal operations, set up _The Uncommons_, create our databases, build out our web presence, and position ourselves for the _Sprout_ phase, ideally within 8 weeks. This will require raising commitments for the \$34k we will need to staff that phase. Equally important, we will complete our initial projects, which will serve as tangible proof of our effectiveness to potential supporters.

During the 8-week _Sprout_ phase, we will create a comprehensive calendar of funding deadlines and proactively communicate with funders to prioritize our grant-writing efforts. We will also populate the database with as much information as we can gather and soft-launch _The Uncommons_. At the end of the  phase, we will provide a detailed report to our umbrella organizations and all funders/sponsors.

We have already identified almost 100 grants and sponsorships (see @sec-potential-funders) for which we meet the basic requirements. These include grants from the State of Oregon (e.g. Oregon Health Authority), Oregon healthcare companies (Legacy, Pacific Source, Cambia, etc.), and a mixture of private and public foundations and trusts. We have missed the 2024 funding cycle for some of these, but many have multiple cycles per year or do not run in cycles. Some of these are small pots of money, and others regularly award hundreds of thousands of dollars. We will also collect sliding-scale fees for using *The Uncommons* co-working spaces.

During our _Grow_ phase, we hope to show that we can collect, analyze, and disseminate information for and about the adult autistic community with a very high level of capacity and efficiency. We hope this expertise will enable us to secure outside contracts as subject matter experts, analysts, and report writers, providing another avenue for revenue. We will complete the Grow phase with a report to our umbrella organization and our financial supporters.
